### ISSUE TITLE
帮我看下怎么回事

### ISSUE THREAD

**Issue by ferrior30** [easemob/hyphenate-full-cocoapods#5]
[!] /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/easemob/hyphenate-full-cocoapods.git /var/folders/vb/4jwmz2ps29g11q4yn6lx0qmc0000gn/T/d20160622-54430-sv9tq7 --template= --single-branch --depth 1

Cloning into '/var/folders/vb/4jwmz2ps29g11q4yn6lx0qmc0000gn/T/d20160622-54430-sv9tq7'...
error: RPC failed; curl 56 SSLRead() return error -9806
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed

**Comment by cheng77** [comment]
/Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/Hyphenate_CN/HyphenateFullSDK/lib/libHyphenateFullSDK.a(emdatabase.o)
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/HyphenateFullSDK/HyphenateFullSDK/lib/libHyphenateFullSDK_x86_64.a(emdatabase.o)
duplicate symbol __ZTVN7easemob10EMDatabaseE in:
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/Hyphenate_CN/HyphenateFullSDK/lib/libHyphenateFullSDK.a(emdatabase.o)
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/HyphenateFullSDK/HyphenateFullSDK/lib/libHyphenateFullSDK_x86_64.a(emdatabase.o)
duplicate symbol _OBJC_CLASS_$_easemobvideo in:
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/Hyphenate_CN/HyphenateFullSDK/lib/libHyphenateFullSDK.a(easemobvideo.o)
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/HyphenateFullSDK/HyphenateFullSDK/lib/libHyphenateFullSDK_x86_64.a(easemobvideo.o)
duplicate symbol _OBJC_METACLASS_$_easemobvideo in:
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/Hyphenate_CN/HyphenateFullSDK/lib/libHyphenateFullSDK.a(easemobvideo.o)
    /Users/tsou/Documents/我的资料文件/游聊项目/YouTalkApp/Pods/HyphenateFullSDK/HyphenateFullSDK/lib/libHyphenateFullSDK_x86_64.a(easemobvideo.o)
ld: 297 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
